import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import Offer from './components/Offer/Offer';
import WhatsAppFloating from './components/WhatsAppFloating';


export const metadata = {
  title: 'Kashi Patent',
  description: 'Generated by Kashi Patent',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
        <WhatsAppFloating />
      </body>
    </html>
  )
}
